# Generated by Django 5.0.6 on 2024-05-20 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academyname', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'academy',
                'db_table_comment': '学院表',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'course',
                'db_table_comment': '学生课程表',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StuCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.IntegerField()),
                ('courseid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stu_cours',
                'db_table_comment': '连接学生表和课程表',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(db_column='ID', db_comment='学生学号', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=5, unique=True)),
                ('gender', models.CharField(db_comment='性别', max_length=1)),
                ('academyid', models.IntegerField(blank=True, db_comment='所属学院,与学院表的id建立连接', null=True)),
                ('entrydate', models.DateField(db_comment='入学日期')),
                ('password', models.IntegerField(db_comment='登陆密码')),
            ],
            options={
                'db_table': 'student',
                'db_table_comment': '学生表',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CourseAcademy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academyid', models.ForeignKey(db_column='academyid', on_delete=django.db.models.deletion.DO_NOTHING, to='app01.academy')),
                ('courseid', models.ForeignKey(db_column='courseid', on_delete=django.db.models.deletion.DO_NOTHING, to='app01.course')),
            ],
            options={
                'db_table': 'course_academy',
                'db_table_comment': '连接学院表和课程表',
                'managed': True,
            },
        ),
    ]
